export const SavanaImages = {
  acacia: 'images/acacia.jpg',
  acaciaBig: 'images/acacia-big.jpg',
  baoba: 'images/baoba.jpg',
  baobaBig: 'images/baoba-big.jpg',
  gnu: 'images/gnu.jpg',
  gnuBig: 'images/gnu-big.jpg',
  capim: 'images/capim.jpg',
  capimBig: 'images/capim-big.jpg',
  elefante: 'images/elefante.jpg',
  elefanteBig: 'images/elefante-big.jpg',
  girafa: 'images/girafa.jpg',
  girafaBig: 'images/girafa-big.jpg',
  kopen: 'images/kopen.png',
  leao: 'images/leao.jpg',
  leaoBig: 'images/leao-big.jpg',
  loboGuara: 'images/lobo-guara.jpg',
  loboGuaraBig: 'images/lobo-guara-big.jpg',
  localizacaoSavanas: 'images/localizacao-savanas.png',
  pequizeiro: 'images/pequizeiro.jpg',
  pequizeiroBig: 'images/pequizeiro-big.jpg',
  savana: 'images/savana.png',
  buriti: 'images/buriti.jpg',
  buritiBig: 'images/buriti-big.jpg'
};